services:
  collapser:
    image: python:2.7-slim
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true # Keep stdin open for interactive shell
    tty: true        # Allocate a pseudo-TTY
    command: >
      bash -c "
        # Install minimal dependencies detected in the codebase
        pip install --upgrade pip==20.3.4 &&
        pip install textblob==0.15.3 nltk==3.4.5 &&
        
        # Download only required NLTK data for TextBlob
        python -c 'import nltk; nltk.download(\"punkt\"); nltk.download(\"averaged_perceptron_tagger\")' &&

        # Keep container running after setup
        echo 'Setup complete. Container running. Use docker-compose exec collapser bash to get a shell.' &&
        tail -f /dev/null
      "
    environment:
      - PYTHONIOENCODING=utf-8